-- Billu Oracle seed demo
-- Pobla datos minimos para customer-summary y customer-categorization.

WHENEVER SQLERROR EXIT SQL.SQLCODE

DELETE FROM DLK_CUSTOMER_SEGMENT_SNAPSHOT;
DELETE FROM DLK_CARD_STATUS;
DELETE FROM DLK_TRANSACTION;
DELETE FROM DLK_MONTHLY_BALANCE;
DELETE FROM DLK_CUSTOMER_PRODUCT_SNAPSHOT;
DELETE FROM DLK_MERCHANT_HOMOLOGATION;
DELETE FROM DLK_CUSTOMER;

INSERT INTO DLK_CUSTOMER (
  REWARDS_ID, ACCOUNT_STATUS, OPENING_DATE, STATE_NAME, MUNICIPALITY_NAME,
  GENDER_CODE, BIRTH_DATE, AGE_YEARS, SOURCE_SYSTEM, SOURCE_SPREADSHEET_ID,
  SOURCE_SHEET_NAME, INGESTION_BATCH_ID
) VALUES (
  'ABC123', 'ACTIVE', DATE '2026-01-10', 'Nuevo Leon', 'Monterrey',
  'F', DATE '1991-04-18', 34, 'LOCAL_ORACLE', 'seed-demo', 'customer',
  'seed-20260423'
);

INSERT INTO DLK_CUSTOMER (
  REWARDS_ID, ACCOUNT_STATUS, OPENING_DATE, STATE_NAME, MUNICIPALITY_NAME,
  GENDER_CODE, BIRTH_DATE, AGE_YEARS, SOURCE_SYSTEM, SOURCE_SPREADSHEET_ID,
  SOURCE_SHEET_NAME, INGESTION_BATCH_ID
) VALUES (
  'XYZ789', 'ACTIVE', DATE '2026-02-05', 'Jalisco', 'Guadalajara',
  'M', DATE '1987-09-02', 38, 'LOCAL_ORACLE', 'seed-demo', 'customer',
  'seed-20260423'
);

INSERT INTO DLK_CUSTOMER (
  REWARDS_ID, ACCOUNT_STATUS, OPENING_DATE, STATE_NAME, MUNICIPALITY_NAME,
  GENDER_CODE, BIRTH_DATE, AGE_YEARS, SOURCE_SYSTEM, SOURCE_SPREADSHEET_ID,
  SOURCE_SHEET_NAME, INGESTION_BATCH_ID
) VALUES (
  'LMN456', 'CANCELLED', DATE '2026-03-01', 'Ciudad de Mexico', 'Benito Juarez',
  'F', DATE '1994-12-11', 31, 'LOCAL_ORACLE', 'seed-demo', 'customer',
  'seed-20260423'
);

INSERT INTO DLK_CUSTOMER (
  REWARDS_ID, ACCOUNT_STATUS, OPENING_DATE, STATE_NAME, MUNICIPALITY_NAME,
  GENDER_CODE, BIRTH_DATE, AGE_YEARS, SOURCE_SYSTEM, SOURCE_SPREADSHEET_ID,
  SOURCE_SHEET_NAME, INGESTION_BATCH_ID
) VALUES (
  'QRS222', 'ACTIVE', DATE '2026-03-20', 'Nuevo Leon', 'San Nicolas',
  'M', DATE '1998-06-27', 27, 'LOCAL_ORACLE', 'seed-demo', 'customer',
  'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_PRODUCT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, PRODUCT_CODE, PRODUCT_LABEL, PRODUCT_ACTIVE_FLAG,
  PRODUCT_BALANCE_AMOUNT, ACCOUNT_STATUS, SOURCE_SYSTEM, INGESTION_BATCH_ID
) VALUES (
  'ABC123', DATE '2026-03-31', 'SAVINGS', 'Cuenta Ahorro', 'Y',
  15000, 'ACTIVE', 'LOCAL_ORACLE', 'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_PRODUCT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, PRODUCT_CODE, PRODUCT_LABEL, PRODUCT_ACTIVE_FLAG,
  PRODUCT_BALANCE_AMOUNT, ACCOUNT_STATUS, SOURCE_SYSTEM, INGESTION_BATCH_ID
) VALUES (
  'ABC123', DATE '2026-03-31', 'CREDIT_CARD', 'Tarjeta Azul', 'Y',
  3200, 'ACTIVE', 'LOCAL_ORACLE', 'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_PRODUCT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, PRODUCT_CODE, PRODUCT_LABEL, PRODUCT_ACTIVE_FLAG,
  PRODUCT_BALANCE_AMOUNT, ACCOUNT_STATUS, SOURCE_SYSTEM, INGESTION_BATCH_ID
) VALUES (
  'XYZ789', DATE '2026-03-31', 'SAVINGS', 'Cuenta Ahorro', 'Y',
  9800, 'ACTIVE', 'LOCAL_ORACLE', 'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_PRODUCT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, PRODUCT_CODE, PRODUCT_LABEL, PRODUCT_ACTIVE_FLAG,
  PRODUCT_BALANCE_AMOUNT, ACCOUNT_STATUS, SOURCE_SYSTEM, INGESTION_BATCH_ID
) VALUES (
  'XYZ789', DATE '2026-03-31', 'INVESTMENT', 'Inversion 90D', 'Y',
  25000, 'ACTIVE', 'LOCAL_ORACLE', 'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_PRODUCT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, PRODUCT_CODE, PRODUCT_LABEL, PRODUCT_ACTIVE_FLAG,
  PRODUCT_BALANCE_AMOUNT, ACCOUNT_STATUS, SOURCE_SYSTEM, INGESTION_BATCH_ID
) VALUES (
  'LMN456', DATE '2026-03-31', 'BASIC', 'Cuenta Basica', 'N',
  1200, 'CANCELLED', 'LOCAL_ORACLE', 'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_PRODUCT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, PRODUCT_CODE, PRODUCT_LABEL, PRODUCT_ACTIVE_FLAG,
  PRODUCT_BALANCE_AMOUNT, ACCOUNT_STATUS, SOURCE_SYSTEM, INGESTION_BATCH_ID
) VALUES (
  'QRS222', DATE '2026-03-31', 'SAVINGS', 'Cuenta Ahorro', 'Y',
  3400, 'ACTIVE', 'LOCAL_ORACLE', 'seed-20260423'
);

INSERT INTO DLK_MONTHLY_BALANCE (
  REWARDS_ID, BALANCE_MONTH, BALANCE_AMOUNT, MONTH_HEADER_LABEL,
  IS_IMPUTED_FLAG, SOURCE_SYSTEM, SOURCE_SPREADSHEET_ID, SOURCE_SHEET_NAME,
  INGESTION_BATCH_ID
) VALUES (
  'ABC123', DATE '2026-01-31', 12000, '2026-01', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423'
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'ABC123', DATE '2026-02-28', 14100, '2026-02', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'ABC123', DATE '2026-03-31', 15000, '2026-03', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'XYZ789', DATE '2026-01-31', 0, '2026-01', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'XYZ789', DATE '2026-02-28', 18000, '2026-02', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'XYZ789', DATE '2026-03-31', 34800, '2026-03', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'LMN456', DATE '2026-03-31', 1200, '2026-03', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_MONTHLY_BALANCE VALUES (
  DEFAULT, 'QRS222', DATE '2026-03-31', 3400, '2026-03', 'N',
  'LOCAL_ORACLE', 'seed-demo', 'monthly-balance', 'seed-20260423',
  SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION (
  REWARDS_ID, TRANSACTION_DATE, ABONO_AMOUNT, CARGO_AMOUNT, DESCRIPTION_TEXT,
  DESCRIPTION_CODE_TEXT, OPERATOR_TEXT, ECOMMERCE_FLAG, PHYSICAL_STORE_FLAG,
  MERCHANT_CATEGORY_CODE, MERCHANT_CATEGORY_DESC, SOURCE_MONTH, SOURCE_FILE_LABEL,
  SOURCE_SPREADSHEET_ID, SOURCE_SHEET_ID, INGESTION_BATCH_ID
) VALUES (
  'ABC123', DATE '2026-01-12', 2500, 0, 'Nomina enero',
  'PAYROLL', 'BILLU', 'N', 'N', 'PAYROLL', 'Abono nomina', '2026-01',
  'seed-demo', 'seed-demo', 1, 'seed-20260423'
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'ABC123', DATE '2026-01-15', 0, 280, 'Supermercado',
  'POS', 'HEB', 'N', 'Y', 'GROCERY', 'Supermercado', '2026-01',
  'seed-demo', 'seed-demo', 1, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'ABC123', DATE '2026-01-22', 0, 420, 'Gasolina',
  'POS', 'OXXO GAS', 'N', 'Y', 'FUEL', 'Gasolinera', '2026-01',
  'seed-demo', 'seed-demo', 1, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'ABC123', DATE '2026-02-02', 0, 760, 'Marketplace',
  'ECOM', 'AMAZON', 'Y', 'N', 'ECOM', 'Compra ecommerce', '2026-02',
  'seed-demo', 'seed-demo', 2, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'XYZ789', DATE '2026-02-20', 0, 550, 'Restaurante',
  'POS', 'SONORA GRILL', 'N', 'Y', 'DINING', 'Restaurante', '2026-02',
  'seed-demo', 'seed-demo', 2, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'XYZ789', DATE '2026-03-05', 6000, 0, 'Transferencia recibida',
  'TRANSFER', 'BILLU', 'N', 'N', 'TRANSFER', 'Abono SPEI', '2026-03',
  'seed-demo', 'seed-demo', 3, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'QRS222', DATE '2026-03-21', 1800, 0, 'Primer deposito',
  'TRANSFER', 'BILLU', 'N', 'N', 'TRANSFER', 'Abono inicial', '2026-03',
  'seed-demo', 'seed-demo', 3, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'QRS222', DATE '2026-03-24', 0, 220, 'Conveniencia',
  'POS', 'OXXO', 'N', 'Y', 'CONVENIENCE', 'Tienda conveniencia', '2026-03',
  'seed-demo', 'seed-demo', 3, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_TRANSACTION VALUES (
  DEFAULT, 'QRS222', DATE '2026-04-02', 0, 180, 'Streaming',
  'ECOM', 'SPOTIFY', 'Y', 'N', 'DIGITAL', 'Suscripcion digital', '2026-04',
  'seed-demo', 'seed-demo', 4, 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_CARD_STATUS (
  REWARDS_ID, CUT_DATE, HAS_PHYSICAL_CARD_FLAG, HAS_DIGITAL_CARD_FLAG,
  HAS_RECENT_PHYSICAL_USAGE_FLAG, HAS_RECENT_DIGITAL_USAGE_FLAG, CARD_STATUS,
  SOURCE_SYSTEM, SOURCE_SPREADSHEET_ID, SOURCE_SHEET_NAME, INGESTION_BATCH_ID
) VALUES (
  'ABC123', DATE '2026-03-31', 'Y', 'N', 'Y', 'N', 'ACTIVE',
  'LOCAL_ORACLE', 'seed-demo', 'card-status', 'seed-20260423'
);

INSERT INTO DLK_CARD_STATUS VALUES (
  DEFAULT, 'XYZ789', DATE '2026-03-31', 'Y', 'N', 'N', 'N', 'DORMANT',
  'LOCAL_ORACLE', 'seed-demo', 'card-status', 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_CARD_STATUS VALUES (
  DEFAULT, 'LMN456', DATE '2026-03-31', 'N', 'N', 'N', 'N', 'NO_CARD',
  'LOCAL_ORACLE', 'seed-demo', 'card-status', 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_CARD_STATUS VALUES (
  DEFAULT, 'QRS222', DATE '2026-03-31', 'N', 'Y', 'N', 'Y', 'ACTIVE',
  'LOCAL_ORACLE', 'seed-demo', 'card-status', 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_MERCHANT_HOMOLOGATION (
  RAW_DESCRIPTION_TEXT, RAW_OPERATOR_TEXT, MERCHANT_CATEGORY_CODE,
  MERCHANT_CATEGORY_LABEL, MERCHANT_GROUP_LABEL, ACTIVE_FLAG, SOURCE_SYSTEM,
  SOURCE_SPREADSHEET_ID, SOURCE_SHEET_NAME, INGESTION_BATCH_ID
) VALUES (
  'SUPERMERCADO', 'HEB', 'GROCERY', 'Supermercado', 'GASTO HOGAR',
  'Y', 'LOCAL_ORACLE', 'seed-demo', 'merchant-homo', 'seed-20260423'
);

INSERT INTO DLK_MERCHANT_HOMOLOGATION VALUES (
  DEFAULT, 'RESTAURANTE', 'SONORA GRILL', 'DINING', 'Restaurante',
  'SALIDAS', 'Y', 'LOCAL_ORACLE', 'seed-demo', 'merchant-homo',
  'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_CUSTOMER_SEGMENT_SNAPSHOT (
  REWARDS_ID, SNAPSHOT_DATE, CURRENT_BALANCE_AMOUNT, BALANCE_AVG_3M,
  TOTAL_TRANSACTIONS, ABONOS_COUNT_30D, CARGOS_COUNT_30D, TENURE_DAYS,
  SEGMENT_ID, SEGMENT_LABEL, SEGMENT_RULE_TEXT, RECOMMENDED_CARD,
  RECOMMENDED_CARD_BENEFITS, TRANSACTION_PROFILE, MISSING_PRODUCTS_TEXT,
  SUGGESTED_CAMPAIGN, INGESTION_BATCH_ID
) VALUES (
  'ABC123', DATE '2026-03-31', 18200, 13700, 4, 1, 3, 80,
  'Exploradores', 'Exploradores', 'Saldo medio y actividad estable',
  'Tarjeta Azul', 'Cashback base y MSI', 'DIGITAL_MIX',
  'Inversion, Tarjeta de credito', 'Cross-sell inversion inicial',
  'seed-20260423'
);

INSERT INTO DLK_CUSTOMER_SEGMENT_SNAPSHOT VALUES (
  DEFAULT, 'XYZ789', DATE '2026-03-31', 34800, 17600, 2, 1, 1, 54,
  'Aliados_Premium', 'Aliados Premium', 'Saldo alto y portafolio robusto',
  'Tarjeta Black', 'Acceso lounge y puntos premium', 'WEALTH_BUILDER',
  '', 'Campana wealth premium', 'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_CUSTOMER_SEGMENT_SNAPSHOT VALUES (
  DEFAULT, 'LMN456', DATE '2026-03-31', 1200, 1200, 0, 0, 0, 30,
  'Constructores', 'Constructores', 'Cliente de bajo saldo en reactivacion',
  'Tarjeta Base', 'Linea inicial y control de gasto', 'LOW_ACTIVITY',
  'Tarjeta de credito', 'Reactivacion con tarjeta inicial',
  'seed-20260423', SYSTIMESTAMP
);

INSERT INTO DLK_CUSTOMER_SEGMENT_SNAPSHOT VALUES (
  DEFAULT, 'QRS222', DATE '2026-03-31', 3400, 3400, 3, 1, 2, 11,
  'Exploradores', 'Exploradores', 'Cliente nuevo con uso digital acelerado',
  'Tarjeta Digital', 'Control desde app y recompensas digitales',
  'DIGITAL_FIRST', 'Nomina', 'Campana de dispersion de nomina',
  'seed-20260423', SYSTIMESTAMP
);

COMMIT;
